### ISSUE TITLE
Ios build failed when this library is used

### ISSUE THREAD

**Issue by navneet-sandhu** [shoumma/react-native-off-canvas-menu#10]
Hello guys help me out to use this library for IOS, its working fine on android.
Error faced in IOS build is below:
this3.props.handleMenu is not a function. (In '_this3.props.handleMenu()', '_this3.props.handleMenu' is undefined)

**Comment by thg303** [comment]
probably forget setting the props. with some source code it would be easier to judge /help.

**Comment by ArfaouiHamouda** [comment]
@navneet-sandhu  did you solve this problem yet ? i want to make sure if it supports IOS , Thanks
