### ISSUE TITLE
undefined is not an object (evaluating '_react3.default.PropTypes.bool')

### ISSUE THREAD

**Issue by phatnguyenbg** [shoumma/react-native-off-canvas-menu#13]
undefined is not an object (evaluating '_react3.default.PropTypes.bool')
How can i fix it?
When I check import { OffCanvasReveal } from "react-native-off-canvas-menu";
OffCanvasReveal or OffCanvas3D it fails to me

**Comment by macanhajc** [comment]
Go to "node-modules/react-native-off-canvas-menu" open offcanvas3d.js and offcanvasReveal.js add `import PropTypes from 'prop-types'` and change `React.PropTypes` to `PropTypes`  on bouth

**Comment by macanhajc** [comment]
Go to "node-modules/react-native-off-canvas-menu" open offcanvas3d.js and offcanvasReveal.js add `import PropTypes from 'prop-types'` and change `React.PropTypes` to `PropTypes`  on bouth

**Comment by hanxf3** [comment]
Please open  offcanvas3d.js and offcanvasReveal.js and change
![image](https://user-images.githubusercontent.com/34429818/34245748-5089d75e-e666-11e7-94e4-c0a214b7fcc8.png)
into
![image](https://user-images.githubusercontent.com/34429818/34245760-61123e54-e666-11e7-9097-826b05c03a24.png)

**Comment by Drakezair** [comment]
i tried that options and the error still happen

**Comment by hanxf3** [comment]
You can try my method.The component has other problems.For example,it will come back when you touch any position  on the screen .

**Comment by Drakezair** [comment]
i ready tried and return this
![captura de pantalla 25](https://user-images.githubusercontent.com/33181147/34370033-3221850c-ea97-11e7-9626-dbae3ca853f7.png)


pls help

**Comment by hanxf3** [comment]
是原组件的代码有问题，offcanvas3d.js要修改，offcanvas.js同理

**Comment by mcblum** [comment]
Also seeing this - latest version on a brand new app.

**Comment by vickvasquez** [comment]
Modify both files
```js
//OffCanvasReveal.js
import PropTypes from 'prop-types'

OffCanvasReveal.propTypes = {
  active: PropTypes.bool.isRequired,
  onMenuPress: PropTypes.func.isRequired,
  menuItems: PropTypes.array.isRequired,
  backgroundColor: PropTypes.string,
  menuTextStyles: PropTypes.object,
  handleBackPress: PropTypes.bool
}
```

```js
//OffCanvas3D.js
import PropTypes from 'prop-types'

OffCanvas3D.propTypes = {
  active: PropTypes.bool.isRequired,
  onMenuPress: PropTypes.func.isRequired,
  menuItems: PropTypes.array.isRequired,
  backgroundColor: PropTypes.string,
  menuTextStyles: PropTypes.object,
  handleBackPress: PropTypes.bool
}

```
