### ISSUE TITLE
ScrollView is not working

### ISSUE THREAD

**Issue by reactnativedeveloperr** [shoumma/react-native-off-canvas-menu#16]
In renderScene View , my scrollview is not working. Please help

**Comment by lucasunity** [comment]
I faced the same problem on iOS, it seems like a problem with the onStartShouldSetResponder. Resolve as follows:

1- Find the library in youproject / NodeModules / react-native-off-canvas-menu / offcanvas3D

2 - Find in the code this function:

 **onStartShouldSetResponder = {() => true}**

3 - set this function to false:
onStartShouldSetResponder = {() => **this.props.active**}

4 - ScrollView running!

**Comment by Zydiii** [comment]
I faced the same problem on Android. This method nicely fixed the problem. Thank!@lucasunity
