### ISSUE TITLE
What makes this an Android only component?

### ISSUE THREAD

**Issue by rmevans9** [shoumma/react-native-off-canvas-menu#2]
After reading through the code the only thing Android specific I saw was the use of BackAndroid - is that the only reason you call this out as a Android only component? If so, wouldn't it be better to offload the BackAndroid usage to the developer using this component and allow the menu to work on Android and iOS?

**Comment by proshoumma** [comment]
Actually, since I don't have any mac to work with, I really didn't want to publish the component for iOS. If an issue arrive for iOS, I won't be able to tackle the issue. It could become hassle for other developers.

**Comment by osagie** [comment]
Through my testing, I've found that the only issue on iOS is an animation glitch when using the 3d Reveal, I think BackAndroid is simply ignored for iOS devices.

**Comment by ArfaouiHamouda** [comment]
@proshoumma  do you think this would work on IOS because as @rmevans9 said the Only Android Specific thing you used was BackAndroid? did you try anything yet?
