### ISSUE TITLE
OffCanvas3D's animation is incorrect on iOS

### ISSUE THREAD

**Issue by duongifc** [shoumma/react-native-off-canvas-menu#3]
Please help check

**Comment by proshoumma** [comment]
The component is not compatible with iOS yet.

**Comment by ksairi** [comment]
@shoumma I haven't tried yet but it looks amazing :+1:. Congratulations.
I'm about to start using it for React native app for android and iOS. Are you planning to make it compatible with iOS sometime in the near future?
cheers!

**Comment by proshoumma** [comment]
Hi @ksairi, I really don't have any plan to make the library compatible with iOS. But I'm open to pull requests for sure. Please feel free to make a pull request.

**Comment by ArfaouiHamouda** [comment]
@duongifc  did you figure out anything yet ? because i see no reason why Animated won't work correctly on IOS
