### ISSUE TITLE
ScrollView is not work with Canvas Menu

### ISSUE THREAD

**Issue by ayberkanilatsiz** [shoumma/react-native-off-canvas-menu#5]
Hi, My menu view has scrollView also. When i implement canvas-menu , scroll is not working. I'm trying to iOS.

Do you know any solution or has any idea about it?

**Comment by proshoumma** [comment]
On android it's okey. I'm not sure about the iOS as I didn't prepared this for iOS.

**Comment by arfa123** [comment]
As a work-around, you can specify a perspective value (before the rotation) to get a similar looking result on both Android and iOS. Note that the perspective needs to be applied prior to the rotation to get the correct results. You can play around with the values, but likely somewhere between 500 and 1000 will give you the effect you're looking for.

Original code:

transform:[ 
  {rotateY: '45deg'}
]
New code:

transform:[
  {perspective: 500},
  {rotateY: '45deg'}
]
